"""initial tables

Revision ID: 24a68ccd31fb
Revises: 
Create Date: 2026-09-21 00:36:15.770743
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "24a68ccd31fb"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "systems",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("system_name", sa.String(length=100), nullable=False),
        sa.Column("system_code", sa.String(length=50), nullable=False),
        sa.Column("ip", sa.String(length=50), nullable=True),
        sa.Column("port", sa.Integer(), nullable=True),
        sa.Column("account", sa.String(length=100), nullable=True),
        sa.Column("password_encrypted", sa.Text(), nullable=True),
        sa.Column("product_name", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("systems", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_systems_system_code"), ["system_code"], unique=True)

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=True),
        sa.Column("role", sa.String(length=20), server_default="user", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.true(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "change_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("table_name", sa.String(length=50), nullable=False),
        sa.Column("record_id", sa.Integer(), nullable=False),
        sa.Column("field_name", sa.String(length=100), nullable=True),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column(
            "changed_at",
            sa.DateTime(),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("change_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_change_log_action"), ["action"], unique=False)
        batch_op.create_index(batch_op.f("ix_change_log_changed_at"), ["changed_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_change_log_table_name"), ["table_name"], unique=False)

    op.create_table(
        "interfaces",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("interface_id", sa.String(length=50), nullable=False),
        sa.Column("interface_name", sa.String(length=200), nullable=False),
        sa.Column("integration_type", sa.String(length=50), nullable=False),
        sa.Column("process", sa.Text(), nullable=True),
        sa.Column("source_system_id", sa.Integer(), nullable=True),
        sa.Column("target_system_id", sa.Integer(), nullable=True),
        sa.Column("cycle", sa.String(length=20), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="Active", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_system_id"],
            ["systems.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_system_id"],
            ["systems.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("interfaces", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_interfaces_cycle"), ["cycle"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_interfaces_integration_type"), ["integration_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_interfaces_interface_id"), ["interface_id"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_interfaces_source_system_id"), ["source_system_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_interfaces_target_system_id"), ["target_system_id"], unique=False
        )

    op.create_table(
        "upload_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("sheet", sa.String(length=20), server_default="interfaces", nullable=False),
        sa.Column(
            "uploaded_at",
            sa.DateTime(),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("record_count", sa.Integer(), nullable=True),
        sa.Column("skipped_count", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="Success", nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("upload_history")
    with op.batch_alter_table("interfaces", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_interfaces_target_system_id"))
        batch_op.drop_index(batch_op.f("ix_interfaces_source_system_id"))
        batch_op.drop_index(batch_op.f("ix_interfaces_interface_id"))
        batch_op.drop_index(batch_op.f("ix_interfaces_integration_type"))
        batch_op.drop_index(batch_op.f("ix_interfaces_cycle"))

    op.drop_table("interfaces")
    with op.batch_alter_table("change_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_change_log_table_name"))
        batch_op.drop_index(batch_op.f("ix_change_log_changed_at"))
        batch_op.drop_index(batch_op.f("ix_change_log_action"))

    op.drop_table("change_log")
    op.drop_table("users")
    with op.batch_alter_table("systems", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_systems_system_code"))

    op.drop_table("systems")
    # ### end Alembic commands ###
